Resolve ExpressionChangedAfterItHasBeenCheckedError
bitwarden/directory-connector pull request #112
Opened 2021-04-21 07:36 UTC by Hinton

## Objective
When clicking the start or sync buttons angular casts a `ExpressionChangedAfterItHasBeenCheckedError` error. This seems to be caused by the elements referring to themselves using the `appApiAction` directive. By wrapping the buttons in forms and attaching the event to the forms we avoid this error.

2021-04-21 22:16 UTC, eliykat requested changes
Looks good to me and also solves the issue on my machine.

However, the same changes need to be made for the "Test Now" button before we can merge.

I think we can also remove the `id` on the buttons now that they don't reference themselves. (minor nit)

I almost jumped in and made these changes, but I didn't know if that would be a faux pas 😅

2021-04-22 08:10 UTC, Hinton commented
@eliykat Good catch, I have nothing against anyone pushing fixes directly on my branch :) Especially with the time differences. There's also the handy suggestion comments which can easily be applied.

2021-04-22 08:43 UTC, eliykat approved these changes

2021-04-22 09:06 UTC, eliykat commented
Hitting merge on this one so we can get it across to QA before I check out for the night.

2021-04-22 09:06 UTC, merged