Revert ldapjs update, use forked repo instead
bitwarden/directory-connector pull request #133
Opened 2021-06-15 01:13 UTC by eliykat

## Objective

Revert my update to `ldapjs` which I did [here](https://github.com/bitwarden/directory-connector/pull/111). The update appears to have broken syncing 9/10 times for some users. Reverting to our fork until we can diagnose the issue.

2021-06-15 13:46 UTC, cscharf requested changes

2021-06-15 13:46 UTC, cscharf commented on package-lock.json
> +    "node_modules/ldap-filter/node_modules/assert-plus": {
@eliykat , it would seem while you can revert the change to `package.json`, there have been SOOOO many other updates that it would be better to only revert that file and instead `npm i` to regen only the necessary portions of `package-lock.json` so as not to re-introduce prior packages or those handled by the `jslib` refactor since removed from here.

2021-06-16 00:44 UTC, eliykat commented on package-lock.json
> +    "node_modules/ldap-filter/node_modules/assert-plus": {
Maybe I should have said "undo" rather than "revert"... I didn't use `git revert`, instead I did what you've suggested: I updated the line in `package.json` then ran `npm i` again, then committed changes.

I did a rough check of the changes in `package-lock.json` just now to make sure, and these changes all seem to be dependencies of `ldapjs`, I assume triggered by the downgrade.

2021-06-16 10:12 UTC, cscharf approved these changes

2021-06-16 23:02 UTC, merged