Ignore duplicate users with same externalId
bitwarden/directory-connector pull request #152
Opened 2021-09-09 00:41 UTC by eliykat

## Objective

We made some changes [here](https://github.com/bitwarden/directory-connector/pull/136) to throw an error if the directory service contains 2 or more users with the same email address. This is because we don't support duplicate email addresses in Bitwarden.

Some users have reported false positives, where the error was being thrown even though they didn't think that they had more than 1 user with the same email address.

I was able to reproduce this by simply disabling a user in Azure AD. The same user was then fetched twice by `azure-directory.service` and this triggered the error.

## Code changes

* `sync.service` - only throw an error if 2 `userEntry`s have the same email address but _different_ `externalId`s. `externalId`s should be unique to each user, so if the email address and `externalId` are identical, it's probably the same user and we can safely remove the duplicates without throwing the error. This should reduce the incidence of false positives.
* `azure-directory.service` - change the boolean logic of `getDeletedUsers` so that disabled (but not deleted) users are excluded from this user set. This should remove the source of the duplicate to begin with. I wasn't 100% sure which set they should go in, because they are neither "current" nor "deleted", but (a) I don't think it matters too much because they're both concatenated at the end, so as long as there's no overlap, and (b) at a glance, our LDAP and GSuite services treat "deleted" as deleted users only, so this seemed the most consistent.

2021-09-09 20:53 UTC, MGibson1 requested changes
I know we talked about this a bit, but seeing it written out got me more worried about removing entries. Comment discusses new idea

2021-09-09 20:53 UTC, MGibson1 commented on src/services/azure-directory.service.ts
> +                    if (!entry.deleted) {
The difference is do we want to only grab disabled users since the last call, unless force is on. I think probably you're right in your decision to always disable

2021-09-09 20:53 UTC, MGibson1 commented on src/services/sync.service.ts
> +        // UserEntrys with the same email and externalId are removed but otherwise ignored
I'm afraid of removing these entries with just this requirement.

These Entries are glorified structs: Can we instead serialize them and compare the serialized strings? That way we remove only if they really are equivalent.

If they're not, something weird happened and we can't determine which is valid and which is not.

2021-09-10 05:33 UTC, eliykat commented on src/services/sync.service.ts
> +        // UserEntrys with the same email and externalId are removed but otherwise ignored
Yep good call, better to be careful before discarding entries. I've changed this to use `JSON.stringify` and it works as expected. I checked the following caveats but I think they're OK:

* doesn't compare methods or stuff up the prototype chain - fine with us
* the order that properties are stringified can be affected by the order they're initialized/assigned values. However, all the `UserEntry`s are initialized in a consistent manner at the same time, so this should be fine in our case.

2021-09-10 05:41 UTC, eliykat commented on src/services/azure-directory.service.ts
> +                    if (!entry.deleted) {
Not sure I follow you - this `if` statement will exclude a `UserEntry` from the `DeletedUsers` set if the condition is true.

At the moment, disabled users are included in the set because for them, `entry.disabled === true && entry.deleted === false`, so this condition is false. And then they're included again in the `CurrentUsers` set because they're not deleted. So the idea is to take them out of the `DeletedUsers` set to avoid the duplicate.

Let me know if I've misunderstood you.

2021-09-13 20:17 UTC, MGibson1 commented on src/services/azure-directory.service.ts
> +                    if (!entry.deleted) {
I meant to explain what the difference was between `getUsers` and `getDeletedUsers`. Deleted users are pulled using a change token from the last sync (unless force is on), which allows MS to only tell us about updates. `getUsers` just grabs all users.

Now that I re-read that comment, it makes no sense in a vacuum. I was responding to my inner monologue, I guess. What's even worse is I don't think this comment adds anything since I'm just agreeing with you -- sorry

2021-09-13 20:19 UTC, MGibson1 approved these changes
I'm too used to c#, I wasn't thinking about the order of properties -- good catch.

2021-09-13 21:00 UTC, eliykat commented on src/services/azure-directory.service.ts
> +                    if (!entry.deleted) {
I hadn't considered that, so good to know! And don't worry, we spend all day in our own heads 😆

2021-09-13 21:00 UTC, merged