Don't flag deleted users as duplicates
bitwarden/directory-connector pull request #181
Opened 2021-11-29 20:07 UTC by differsthecat

## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fixes an issue where a duplicate email error is being thrown. After a lot of investigation, the root cause of this has been determined to be deleted users; AD unfortunately allows emails to be duplicated for deleted users. Additional context here: https://app.asana.com/0/1169444489336079/1201410771133282/f

## Code changes

* **sync.service.ts** Add a condition to only add a user to the duplicateEmails array if the user is not deleted.

## Screenshots

## Testing requirements

## Before you submit
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-11-29 20:15 UTC, differsthecat commented
@MGibson1 , @eliykat It looks like you have both worked on this part of the code before, I would appreciate your thoughts on this!

2021-11-29 21:39 UTC, eliykat commented
Is this a bug? Directory Connector deprovisions users as well. It seems like the usual concern about duplicate email addresses applies here as well. That is, emails are unique identifiers in Bitwarden, and Bitwarden can't tell two accounts apart if they use the same email.

For example:
* User A is active in the directory service and has been provisioned with a Bitwarden account
* User A is then deleted from the directory service, and User B is added using the same email
* bwdc tries to sync these changes - I'm not sure what would happen at the moment, but my guess is that no deprovisioning would occur. User A would still have access to their Bitwarden account because the email address is still present in AD. User B does not get invited because they don't appear as a new user. (Much worse than a duplicate email error.)

Note that the `removeDuplicateUsers` method compares a stringified version of the `UserEntry` object, so we're already comparing all user properties that are available to us.

I think this is either a problem with the user's directory service configuration, or a larger problem with bwdc. Not sure what the answer is.

2021-11-29 22:50 UTC, differsthecat commented
@eliykat Those are great points! With what is currently happening there is definitely a bug. We may have to approach it differently than I did here though.

There are a couple scenarios where the client ends up in a state where they can not sync anything at all if there are users that are deleted that have email conflicts with each other. 
Another way we can tackle this is to apply the users filter to the deleted users query. Currently all deleted users are grabbed, regardless of if they are deleted or not. So even if you filter down users to one single user, if there are conflicts in deleted users between themselves, it throws the duplicate error.

We can also change how we look for duplicates and throw an error if a non-deleted user conflicts with a deleted user, but allow deleted users to be duplicated between each other.

2021-11-29 22:58 UTC, differsthecat commented
@eliykat Here's the code in question that neglects to apply the filter to the deleted users:
https://github.com/bitwarden/directory-connector/blob/abc68e8ef93642490b4e0ccfbb8cee0ef0a44719/src/services/ldap-directory.service.ts#L82
Up on line 70 of this function, the supplied filter is applied to the regular users query.

2021-12-01 02:03 UTC, differsthecat commented
> @eliykat Here's the code in question that neglects to apply the filter to the deleted users:
> 
> https://github.com/bitwarden/directory-connector/blob/abc68e8ef93642490b4e0ccfbb8cee0ef0a44719/src/services/ldap-directory.service.ts#L82
> 
> 
> Up on line 70 of this function, the supplied filter is applied to the regular users query.

I spent some time playing with this, and an issue with adding the user's filter to the deleted users query is that in AD deleted users are missing many fields that non-deleted users have (such as sAMAccountName, givenName) so deleted users can get removed when they are not expected to. This would need a more creative solution and is out of scope of this for now, so I reverted those changes.

2021-12-01 02:09 UTC, differsthecat commented on src/services/sync.service.ts
> +                }
This may be a bit tricky to read, but:
- If a user is active (not deleted) and there is another user with the same email (deleted or not), the duplicate error is thrown.
- If a user is deleted and there are any other users that are also deleted with the same email, no error is thrown.

This will fix the case that clients are seeing where deleted users that don't conflict with active users are causing a sync to fail.

2021-12-01 03:19 UTC, eliykat requested changes

2021-12-01 03:19 UTC, eliykat commented on src/services/sync.service.ts
> +        // UserEntrys with the same email but different properties will throw an error
Update to describe new logic, e.g.

```suggestion
        // UserEntrys with the same email but different properties will throw an error, unless they are all in a deleted state.
```

2021-12-01 03:19 UTC, eliykat commented on src/services/sync.service.ts
> +                    // UserEntrys with the same email but are all deleted are ignored but tracked
```suggestion
                    // UserEntrys with duplicate email will not throw an error if they are all deleted. They will be synced.
```

2021-12-01 03:19 UTC, eliykat commented on src/services/sync.service.ts
> +                    // UserEntrys that are not deleted but there's a deleted entry with same email error
```suggestion
                    // Check that active UserEntry does not conflict with a deleted UserEntry
```

2021-12-01 03:25 UTC, eliykat approved these changes
Nice work!

2021-12-01 03:58 UTC, merged