[refactor] Implement StateService
bitwarden/directory-connector pull request #192
Opened 2021-12-16 00:01 UTC by addisonbeck

## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

## Code changes

* **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-12-20 19:35 UTC, joseph-flinn commented on .github/workflows/build.yml
> +          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
```suggestion
          dbus-launch --sh-syntax
          
          echo -n "" | /usr/bin/gnome-keyring-daemon --login
          /usr/bin/gnome-keyring-daemon --components=secrets --start
```

I don't believe `eval` is needed here. It is normally used to evaluate a command that is stored in a variable as a string like
```bash
var="ls -alth"
eval $var
```

2021-12-20 19:40 UTC, differsthecat commented on .github/workflows/build.yml
> +          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
I'll give it a try and see if it is still happy with it!

2021-12-20 19:44 UTC, differsthecat commented on .github/workflows/build.yml
> +          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
It's erroring again, I'm going to add the `eval`'s back

2021-12-20 20:15 UTC, joseph-flinn commented on .github/workflows/build.yml
> +          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
Weird. Ok, we can keep the `eval`'s then.

2021-12-21 14:05 UTC, MGibson1 commented on .github/workflows/build.yml
> +          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
At the least `eval $(dbus-launch --sh-syntax)` is necessary. The application outputs a set of env variables about the currently running dbus session.

I don't believe the others are as there is no output.

2021-12-21 15:37 UTC, MGibson1 requested changes
I don't see anything that would allow for multiple accounts, but I also don't see anything enforcing a single account.

Is multiple org sync from a single instance something we want to enable in the future?

What's the current experience if you set up your DC for an org, then log out and log into another org, set it up, then log out and log in to the first -- is your config maintained? Is that what we want?

2021-12-21 15:37 UTC, MGibson1 commented on src/program.ts
> +import { HtmlStorageLocation } from "jslib-common/enums/htmlStorageLocation";
This enum scares me. DC uses electron and lowdb for storage, what's up with the name?

2021-12-21 15:37 UTC, MGibson1 commented on src/program.ts
> +import { HtmlStorageLocation } from "jslib-common/enums/htmlStorageLocation";
Also, it's unused and can be removed

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      await this.stateService.setLastGroupSync(date);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      await this.stateService.setLastSyncHash(hash);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      return await this.stateService.setLastUserSync(date);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      await this.stateService.setGroupDelta(token);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      return this.stateService.setUserDelta(token);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +            await this.stateService.setOneLoginKey(savedConfig.clientSecret);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +            await this.stateService.setOktaKey(savedConfig.token);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +            await this.stateService.setAzureKey(savedConfig.key);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +            await this.stateService.setLdapKey(savedConfig.password);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/configuration.service.ts
> +      await this.stateService.setOrganizationId(id);
No purpose to this `if` statement anymore

2021-12-21 15:37 UTC, MGibson1 commented on src/services/auth.service.ts
> +            userId: clientId,
seems a little odd to use clienId here, we don't do anything expecting a Guid, right?

Maybe to be safe this should be `entityId` anyways?

2021-12-21 15:37 UTC, MGibson1 commented on src/services/state.service.ts
> +  }
All this repeated `options =...` stuff is begging for a template method that takes a callback to `get` or `save`

2021-12-21 15:37 UTC, MGibson1 commented on src/services/state.service.ts
> +      `${options.userId}_${SecureStorageKeys.ldap}`,
What do these keys look like in the OSs secrets viewer (like mac's Keychain Access)?

Currently we see something like the attached image, where that item has a field, `account`, that holds identifying information.

Is that how this works?

![image](https://user-images.githubusercontent.com/18214891/146956535-0416a15d-1c45-449b-8aab-e16ec868dd75.png)

2021-12-21 16:04 UTC, differsthecat commented
> I don't see anything that would allow for multiple accounts, but I also don't see anything enforcing a single account.
> 
> Is multiple org sync from a single instance something we want to enable in the future?
> 
> What's the current experience if you set up your DC for an org, then log out and log into another org, set it up, then log out and log in to the first -- is your config maintained? Is that what we want?

This isn't implementing multiple accounts in DC, it's just implementing the changes to state service.

2021-12-21 16:31 UTC, MGibson1 commented
@differsthecat, we're still storing under some account-specific infrastructure. That's why I'm asking what would happen in that multi-user scenario I posed.

I'm wondering if we should wipe the state of all users if you log in as a new user

2021-12-21 17:33 UTC, differsthecat commented
@MGibson1 That's a good point. There could be some value in keeping the account settings when a different one is logged in, as the directory settings are then saved for the previous account. Only if that's a valid use case though.
Do you happen to know off hand if another account is logged in if the directory settings are persisted to the new account? If not, I agree and think we should just wipe the state if a new one is logged in.

2021-12-21 18:12 UTC, differsthecat commented on src/services/state.service.ts
> +      `${options.userId}_${SecureStorageKeys.ldap}`,
Yes, I just checked what it looks like for me and in the `account` field it has items such as `organization.{id}_ldapPassword` for the ldapPassword

2021-12-21 18:27 UTC, differsthecat commented on src/services/state.service.ts
> +  }
Agreed, this is something we probably want to do on the jslib stateService level as well. I'd like to get this PR in for now so that directory connector isn't blocked anymore but definitely an enhancement we can think about doing soon.

2021-12-21 18:44 UTC, differsthecat commented on src/services/configuration.service.ts
> +import { IConfiguration } from "src/models/IConfiguration";
Do you mind if we make this a tech debt item? I was just looking into doing this and we may have to do more than just deleting this service and dropping the directory items in there. I want to get this merged so people are unblocked and I'm afraid I might end up going down a rabbit hole doing this.

2021-12-21 19:53 UTC, MGibson1 commented on src/services/auth.service.ts
> +            userId: clientId,
I don't believe we're doing anything that explicitly expects a guid vs a string in the future, but I believe making this consistent with other clients is a good idea.

Please make sure that the way this is implemented in Desktop is via a userId Guid (pretty sure it is) and change this to match.

2021-12-21 19:53 UTC, MGibson1 commented on src/services/state.service.ts
> +      `${options.userId}_${SecureStorageKeys.ldap}`,
killer that's perfect

2021-12-21 20:22 UTC, MGibson1 commented
Currently logout does not wipe settings, no. Logging in as another org also does not change directory settings.

We need to decide if we want to maintain that behavior or change it. I believe that right now we'd have unique Directory settings per organization login.

2021-12-21 20:50 UTC, differsthecat commented on src/services/auth.service.ts
> +            userId: clientId,
Just checked Desktop and it is using a guid value. I updated directory connector to match 👍

2021-12-22 18:29 UTC, differsthecat commented on src/services/configuration.service.ts
> +import { IConfiguration } from "src/models/IConfiguration";
This has been addressed with the latest commits!

2021-12-22 19:00 UTC, MGibson1 requested changes
One tiny little thing left. Sorry I missed this last time

2021-12-22 19:00 UTC, MGibson1 commented on src/services/stateMigration.service.ts
> +    const userId = await this.storageService.get<string>("entityId");
Should we convert these strings to constants in either the `Keys` or `ClientKeys` hashes?

2021-12-22 19:57 UTC, differsthecat commented on src/services/stateMigration.service.ts
> +    const userId = await this.storageService.get<string>("entityId");
Yep, all of the keys in the migration service are now constants

2021-12-22 20:14 UTC, MGibson1 approved these changes

2021-12-22 20:16 UTC, merged