Only get users for includeGroup filter
bitwarden/directory-connector pull request #205
Opened 2022-01-13 14:58 UTC by differsthecat

## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Azure AD gets all users for an entire directory regardless of the user filters provided, and then sends a separate api request to Azure per user to determine group membership to filter out unwanted users. This takes an unnecessarily long amount of time for clients that only want to sync a few users and have many many more users in their directory.

With this change, if the `includeGroup` filter is provided, only the users that belong to that group are synced over. This eliminates the need to check group membership on a per user basis.

I left the sync process the same for the other filter types as there was not the same advantages for those cases.

I also left the process for getting deleted users the same because those functions rely on the delta token, which is not a supported by the Graph API for group members.

Even with those considerations, for an Azure AD with only 8 users, the sync time was reduced from an average of **2.3 seconds** down to **1 second**. This difference should be even more pronounced for larger instances that only sync over a select number of groups.

Ticket: https://app.asana.com/0/1201211497354246/1201456218559784
Issue: https://github.com/bitwarden/directory-connector/issues/83

## Code changes

- **src/services/azure-directory.service.ts:** 
## Testing requirements

Ensure that Azure AD syncs properly with all possible user filters

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-17 00:25 UTC, eliykat requested changes
This is a good improvement, nice work @differsthecat!

Out of scope for this PR, but I wonder whether there is a better way of handling the `ExcludeGroup` case. e.g. get the transitive memberships of the excluded groups, get all users, then filter the users locally. The number of api calls would be roughly proportionate to the number of excluded groups rather than the number of users in the entire organization.

Please also flag this to QA especially, any accidental change in functionality could cause a large number of accounts to be unintentionally (de)provisioned which could cause some headaches.

2022-01-17 00:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> -      return false;
Maybe we should throw an error in this case, because this should never occur - and if it does, we probably want to abort syncing as this will invalidate our assumptions in this method.

2022-01-17 00:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +    if (memberGroups.value.length > 0 && setFilter[0] === UserSetType.ExcludeGroup) {
You're checking the `UserSetType` in both `if` statements. Also, I don't think that we want to do this api call at all unless `setFilter[0] === UserSetType.ExcludeGroup`. I think you could move this check into the same `if` statement as `!checkGroupsFilter`, and just return early if it's not satisfied.

2022-01-17 00:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +      while (true) {
Same comment applies for when you move the other api call into its own method. `while(true)` loops seem bad.

2022-01-18 17:44 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +      while (true) {
Agreed, I'll fix these!

2022-01-18 18:03 UTC, differsthecat commented on src/services/azure-directory.service.ts
> -      return false;
Yeah I removed these thinking they wouldn't be possible conditions anymore, but if I missed anything and it gets to here we should throw an error

2022-01-18 20:52 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +      const userReq = this.client.api("/users" + UserSelectParams);
Updated! There's a slight bit of duplication of some minor things but I feel like it is much more readable now

2022-01-18 20:52 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +      while (true) {
Refactored this code into the `getUsersByResource()` method so there are no more `while(true)`'s.
Also I am open to a better name for that method, that was the best I could come up with 😅

2022-01-18 20:53 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +            if (
Extracted into `isInvalidUser()`

2022-01-18 20:58 UTC, differsthecat commented
@eliykat Thank you for the thorough review! I accidentally deleted one of your comments when I went to delete one of mine :face-palm: but I was able to implement a lot of fixes here! Also awesome idea about how to handle `excludeGroups`, I went ahead and implemented it here! With that implemented there wasn't even a need to keep the code that sent requests via `checkMemberGroups`

2022-01-18 21:39 UTC, eliykat requested changes
Looks great! Just one thing that I think you missed.

2022-01-18 21:39 UTC, eliykat commented on src/services/azure-directory.service.ts
> -      return false;
Reminder to do this if it's called with a group filter. Will be a good safeguard in case it's called from elsewhere in the code, or if someone else misses the refactor.

2022-01-18 21:42 UTC, eliykat commented on src/services/azure-directory.service.ts
> +      while (true) {
I think the name is good! I like that you've abstracted the api call to that one method.

2022-01-18 21:51 UTC, eliykat reviewed
Had a bit more of a think about this as well.

2022-01-18 21:51 UTC, eliykat commented on src/services/azure-directory.service.ts
> +      const userReq = this.client.api("/users" + UserSelectParams);
I think you may be able to reduce this duplication further. Each `for (const user of users)` loop basically does the same thing, but with a different filter:
* IncludeGroup - no filter (filtering is done in the api call)
* ExcludeGroup - not in `usersToExclude`
* users filters - `filterOutUserResult` call

So maybe you can move this loop to a method that takes a filter callback or something similar.

2022-01-18 23:04 UTC, differsthecat commented
> Had a bit more of a think about this as well.

Implemented this!

2022-01-18 23:25 UTC, eliykat requested changes
A few minor comments then good to go!

2022-01-18 23:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +          // filterOutUserResult should only be called if the filter is includeUser or excludeUser
This just restates the `if` condition, I was thinking of something more like

```suggestion
          // Deleted users cannot be filtered by group in Azure AD so we only apply user filters if required
```

...assuming that is correct, that's my understanding of the rationale. Basically replacing the old comment on line 291 that we're now deleting.

2022-01-18 23:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +            if (await this.filterOutUserResult(setFilter, entry)) {
This can be combined into the previous if condition

2022-01-18 23:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +      if (users != null) {
This `if` block is identical in each branch. You can extract it to the bottom of the `if` condition.

2022-01-18 23:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> +    usersToExclude: Set<string>,
Suggest renaming this to `userIdsToExclude` just so it's clear what the `string` is.

2022-01-18 23:25 UTC, eliykat commented on src/services/azure-directory.service.ts
> -      return false;
We decided not to do this so all good

2022-01-19 01:22 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +    usersToExclude: Set<string>,
Done

2022-01-19 01:23 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +      if (users != null) {
Fixed; this is the same condition we did for the deleted users, so I went ahead and removed the comment as it seems a bit unnecessary since it's the same here too.

2022-01-19 01:23 UTC, differsthecat commented on src/services/azure-directory.service.ts
> +            if (await this.filterOutUserResult(setFilter, entry)) {
Fixed; this is the same condition we did for the deleted users, so I went ahead and removed the comment as it seems a bit unnecessary since it's the same here too.

2022-01-19 03:13 UTC, eliykat requested changes

2022-01-19 03:13 UTC, eliykat commented on src/services/azure-directory.service.ts
> -    while (true) {
I like trying to replace the `while (true)` loop, but there's not much point unless you can also refactor the break loop logic on line 160. Currently you're still breaking out of the loop with the `break` statement rather than the `while` condition.

2022-01-19 13:40 UTC, differsthecat commented on src/services/azure-directory.service.ts
> -    while (true) {
Gotcha, I was thinking this way it was still easier to understand. I put it back the way it was.

2022-01-19 20:02 UTC, eliykat approved these changes

2022-01-19 20:05 UTC, merged