[Help] Update links to new pattern
bitwarden/directory-connector pull request #227
Opened 2022-02-08 23:20 UTC by vincentsalucci

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern

## Code changes
- **README.md**: Updated URL to new pattern

## Dependency
- [jslib - [Help] Update links to new pattern](https://github.com/bitwarden/jslib/pull/658)

## Testing requirements
- Make sure URL links don't 404 and take you to the correct page

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-02-08 23:25 UTC, djsmith85 requested changes

2022-02-08 23:25 UTC, djsmith85 commented on README.md
> +We provide detailed documentation and examples for using the Directory Connector CLI in our help center at https://bitwarden.com/help/directory-sync/#command-line-interface.
This link should probably be: https://bitwarden.com/help/directory-sync-cli/

2022-02-08 23:44 UTC, vincentsalucci commented on README.md
> +We provide detailed documentation and examples for using the Directory Connector CLI in our help center at https://bitwarden.com/help/directory-sync/#command-line-interface.
@DanHillesheim @fschillingeriv - Thoughts? The redirect of the existing URL takes you to the URL I replaced it with. However, @djsmith85 makes a **great** point!

2022-02-08 23:54 UTC, DanHillesheim commented on README.md
> +We provide detailed documentation and examples for using the Directory Connector CLI in our help center at https://bitwarden.com/help/directory-sync/#command-line-interface.
Thanks, that is a good point. I will leave that up to Fred though. I think he has final say on help site link destinations. @fschillingeriv What say ye?

2022-02-09 14:34 UTC, fschillingeriv commented on README.md
> +We provide detailed documentation and examples for using the Directory Connector CLI in our help center at https://bitwarden.com/help/directory-sync/#command-line-interface.
Looks like this is specifically for BWDC CLI? In that case, yeah, it'd be best to link to https://bitwarden.com/help/directory-sync-cli/ !

2022-02-09 15:07 UTC, vincentsalucci commented on README.md
> +We provide detailed documentation and examples for using the Directory Connector CLI in our help center at https://bitwarden.com/help/directory-sync/#command-line-interface.
Updated!

2022-02-09 15:39 UTC, djsmith85 approved these changes

2022-02-09 15:59 UTC, merged