Update download artifact action
bitwarden/directory-connector pull request #285
Opened 2022-10-10 14:35 UTC by Eebru-gzy

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Update download artifacts action to latest 
## Code changes

file changed: .github/workflows/release.yml

Update artifact download action version to the most recent

- **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-10-13 19:22 UTC, vgrassia requested changes

2022-10-13 19:22 UTC, vgrassia commented on .github/workflows/enforce-labels.yml
> +            description: "PRs on hold cannot be merged"
```suggestion
          BANNED_LABELS: "hold"
          BANNED_LABELS_DESCRIPTION: "PRs on hold cannot be merged"
```

2022-10-13 19:22 UTC, vgrassia commented on .github/workflows/release.yml
> +        uses: bitwarden/gh-actions/download-artifacts@c850faad0cf6c02a8c0dc46eddde2363fbd6c373a
```suggestion
        uses: bitwarden/gh-actions/download-artifacts@850faad0cf6c02a8c0dc46eddde2363fbd6c373a
```

2023-06-21 13:04 UTC, withinfocus commented
This seems to be in conflict with https://github.com/bitwarden/directory-connector/pull/288.

2023-06-21 14:45 UTC, closed without merging