Fix tests
bitwarden/directory-connector pull request #398
Opened 2024-01-10 19:55 UTC by addisonbeck

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2024-01-10 20:56 UTC, mimartin12 submitted a review, later dismissed

2024-01-11 02:37 UTC, eliykat requested changes

2024-01-11 02:37 UTC, eliykat commented on jest.config.js
> -  coverageDirectory: "coverage",
I'm not really familiar with Jest's code coverage reporting, but do we want to maintain it here? (that said, I don't think I've ever seen a code coverage report from Jest myself, so idk)

2024-01-11 02:37 UTC, eliykat commented on test.setup.ts
> +});
duplicates previous lines 27-29

2024-01-11 02:37 UTC, eliykat commented on tsconfig.json
> +  "include": ["src", "jslib", "scripts", "./**.ts"]
1. Does `scripts` need to be included in the TS compilation? They're all plain JS and I don't think they're used by the app.
2. Why `./**ts`? That'll match everything (I think) which makes all the other items redundant. I would've thought `src` would cover it.

2024-01-11 02:37 UTC, eliykat commented on tsconfig.eslint.json
> +  "include": ["src", "jslib", "scripts", "./**.ts"]
Same question here re the glob pattern

2024-01-11 17:13 UTC, addisonbeck commented on jest.config.js
> +        },
Addressed on https://github.com/bitwarden/directory-connector/pull/398/commits/b321185f7d544e28097333b07356ed7f9758b1e0

2024-01-11 17:16 UTC, addisonbeck commented on jest.config.js
> +        isolatedModules: true,
✅ Implemented: https://github.com/bitwarden/directory-connector/pull/398/commits/0adea2ab8c78c60dd82f54be2c0d5bf44b134879 [Add type checking script and build step from clients](https://github.com/bitwarden/directory-connector/pull/398/commits/0adea2ab8c78c60dd82f54be2c0d5bf44b134879)

2024-01-11 17:18 UTC, addisonbeck commented on jest.config.js
> -  // Also anecdotally improves performance when run locally
**☑️ Implemented:** https://github.com/bitwarden/directory-connector/pull/398/commits/58e1256cc84b1ac452931192e9f77f6b57354830 [Add back comments to jest.config memork leak tweaks](https://github.com/bitwarden/directory-connector/pull/398/commits/58e1256cc84b1ac452931192e9f77f6b57354830)

2024-01-11 17:19 UTC, addisonbeck commented on es2020-transformer.ts
☑️ Implemented: https://github.com/bitwarden/directory-connector/commit/b321185f7d544e28097333b07356ed7f9758b1e0 [Remove es2020-transformer.ts](https://github.com/bitwarden/directory-connector/pull/398/commits/b321185f7d544e28097333b07356ed7f9758b1e0)

2024-01-11 17:28 UTC, addisonbeck commented on jest.config.js
> -  coverageDirectory: "coverage",
📝 **Noted as tech debt**:  [AC-1998](https://bitwarden.atlassian.net/browse/AC-1998?focusedCommentId=49622)

___ 

Here's a copy/paste of my comment there. Let me know if you still think it would be a good idea to "bring back" in this work, but we didn't have any scripts that ran coverage reports and frankly it doesn't seem very useful in Directory Connector to me right now. We'd at least want to upload those reports the way `clients` does, which I'd say is getting out of scope of what I was trying to do here.

> #### [AC-1998] [Directory Connector] Audit GitHub workflows
> Note: I went ahead and added a unit test workflow on [[AC-1743] pt. 2.5 ⮕ Fix the unit tests for good by addisonbeck · Pull Request #398 · bitwarden/directory-connector](https://github.com/bitwarden/directory-connector/pull/398) 
> 
> I kept breaking the tests and didn’t want to step on my own toes anymore 💅
> 
> That said, there is a code coverage step in clients that you can see [here](https://github.com/bitwarden/clients/blob/99022e2baa4692751b1cbdeb96a17a44ea68c1f8/.github/workflows/test.yml#L53-L68) as of the time writing this comment. This is not currently implemented in Directory Connector, and we should determine its usefulness as part of this work. We don’t have great coverage in DC, and the tests we do have can be misleading, but it still may be a good idea to get something going here.

2024-01-11 17:34 UTC, addisonbeck commented on test.setup.ts
> +});
☑️ **Implemented**: https://github.com/bitwarden/directory-connector/pull/398/commits/e5a30197f2f752250638251595335a98cb08992f [Remove duplicate function from test.setup.ts](https://github.com/bitwarden/directory-connector/pull/398/commits/e5a30197f2f752250638251595335a98cb08992f)

2024-01-11 17:39 UTC, addisonbeck commented on tsconfig.json
> +  "include": ["src", "jslib", "scripts", "./**.ts"]
☑️ **Implemented:** https://github.com/bitwarden/directory-connector/pull/398/commits/269372283cb892bd99ef539efdba3be799c029d0 [Adjust include arrays in tsconfig and tsconfig.eslint to avoid over-including](https://github.com/bitwarden/directory-connector/pull/398/commits/269372283cb892bd99ef539efdba3be799c029d0)

___

> Does scripts need to be included in the TS compilation?

No, at least not in `tsconfig.json`. It does in `tsconfig.eslint.json` if we want linting on those files, which seems helpful to have. I took these out of `tsconfig.json`, thanks for the catch.

> Why ./**ts? 

You're right, and that path should just be `./*.ts`. I want it to catch any `.ts` files in the root directory so it will notice things like `test.setup.ts` and (previously before it was delete) the transformer script that jest uses. I adjusted this path in `tsconfig.eslint.json` and removed it from `tsconfig.json`.

2024-01-11 17:40 UTC, addisonbeck commented on tsconfig.eslint.json
> +  "include": ["src", "jslib", "scripts", "./**.ts"]
☑️ Implemented: https://github.com/bitwarden/directory-connector/commit/269372283cb892bd99ef539efdba3be799c029d0 [Adjust include arrays in tsconfig and tsconfig.eslint to avoid over-including](https://github.com/bitwarden/directory-connector/pull/398/commits/269372283cb892bd99ef539efdba3be799c029d0)

___

Explanation on the other comment: https://github.com/bitwarden/directory-connector/pull/398#discussion_r1449194105

2024-01-11 22:05 UTC, eliykat commented on jest.config.js
> -  coverageDirectory: "coverage",
That's cool, we weren't really using it anyway so happy for it to be a follow-up item.

2024-01-11 22:06 UTC, eliykat commented on jest.config.js
> +        isolatedModules: true,
Makes sense!

2024-01-11 22:06 UTC, eliykat approved these changes
Great work!

2024-01-12 19:05 UTC, joseph-flinn approved these changes

2024-01-12 19:05 UTC, merged