Include action to support Checkmarx and Sonar
bitwarden/directory-connector pull request #546
Opened 2024-08-01 17:58 UTC by bwdil

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Implement scanning workflow 

## Objective

[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288) - Deploy scanning workflow organization wide

2024-08-01 19:10 UTC, withinfocus approved these changes
Renovate will grab the updates, but the Action versions you have here are decently out of date.

2024-08-01 19:47 UTC, vgrassia requested changes

2024-08-01 19:47 UTC, vgrassia commented on .github/workflows/scan.yml
> +          ref: ${{  github.event.pull_request.head.sha }}
```suggestion
          ref: ${{ github.event.pull_request.head.sha }}
```

2024-08-01 21:01 UTC, withinfocus approved these changes

2024-08-05 16:12 UTC, vgrassia approved these changes

2024-08-05 16:12 UTC, merged