BRE-141 Refactor Release workflow to split deploy/publish steps
bitwarden/directory-connector pull request #567
Opened 2024-08-30 16:19 UTC by urbinaalex17

## Type of change

- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Split `directory-connector` GitHub Releases from Deploy/Publish.

## Code changes

- **.github/workflows/release.yml:** Remove deploy/publish steps.
- **.github/workflows/publish.yml:** Create new workflow with removed steps from `release.yml`

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2024-09-02 11:54 UTC, michalchecinski commented on .github/workflows/publish.yml
I'm wondering if we need a publish workflow at all in `directory-connector` since nothing is technically published/deployed.

2024-09-02 14:19 UTC, urbinaalex17 commented on .github/workflows/publish.yml
As discussed in today's standup, even though there are no actual publish/deploy steps, we still need to separate the logic to have a standard process across all the repositories.

2024-09-03 14:33 UTC, vgrassia commented on .github/workflows/publish.yml
@urbinaalex17 The Publish workflow can be deleted.  We don't need it if it's not doing anything.  The Release workflow can stay as you have it with the deployment steps removed for consistency.

2024-09-03 15:11 UTC, vgrassia requested changes

2024-09-03 15:11 UTC, vgrassia commented on .github/workflows/release.yml
```suggestion
```

2024-09-03 15:13 UTC, urbinaalex17 commented on .github/workflows/publish.yml
Shouldn't we keep the publish workflow for consistency too?

2024-09-04 15:39 UTC, vgrassia approved these changes

2024-09-05 04:49 UTC, eliykat approved these changes
I don't have a lot of background for this change, but it looks like Github Deployments aren't really relevant to directory-connector because it's a downloadable app only (not hosted anywhere).

2024-09-05 04:49 UTC, merged