Remove npm minor grouping from renovate config
bitwarden/directory-connector pull request #576
Opened 2024-09-02 04:21 UTC by eliykat

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

The renovate config in this repository groups patch and minor updates together. I think this is unhelpful as it has led to this enormous PR (which is failing): https://github.com/bitwarden/directory-connector/pull/353.

I'd rather smaller, easier PRs, even if we have many of them. We don't use this grouping in `clients` either.

The proposal here is to remove this grouping (this PR) and then force renovate to create new update PRs for each dependency (not sure how to do this).

@withinfocus renovate is your area, do you have any feedback on this? Is it going to work how I want?

@bitwarden/team-admin-console-dev this is going to affect the team, so feedback welcome.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2024-09-03 15:49 UTC, withinfocus requested changes
You have it correct -- just remove that group and these will come in individually. I am not sure we do this for NPM anywhere else, but those projects are more-aggressively merged.

2024-09-03 15:49 UTC, withinfocus commented on .github/renovate.json
> -  "enabledManagers": ["github-actions", "npm"],
❌ This removes NPM updates altogether.

2024-09-04 00:00 UTC, eliykat commented on .github/renovate.json
> -  "enabledManagers": ["github-actions", "npm"],
Fixed!

2024-09-04 00:01 UTC, eliykat commented
@withinfocus to clarify, will renovate automatically detect the updated config, close the existing PR, and open the new PRs?

2024-09-04 12:24 UTC, withinfocus approved these changes

2024-09-04 12:25 UTC, withinfocus commented
> @withinfocus to clarify, renovate should automatically detect the updated config, close the existing PR, and open the new PRs?

It'll run again when the config changes, but it might not necessarily make _new_ PRs given the schedule. That's easily worked around there where you just ask for PR creation via the checkboxes at https://github.com/bitwarden/directory-connector/issues/303.

2024-09-04 13:43 UTC, r-tome approved these changes

2024-09-04 20:50 UTC, merged