initial implementation
bitwarden/directory-connector pull request #703
Opened 2024-12-27 15:19 UTC by BTreston

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-27 15:44 UTC, BTreston commented
@eliykat Whenever you're back and able to give this first pass a look over, I just had a few questions:

- it seems like jest doesnt like ECMAScript Modules (which are used in the googleapis) and plugging it into the existing transformer in the jest config didn't seem to fix it. Not sure how to handle the resulting [error](https://stackoverflow.com/questions/51994111/jest-encountered-an-unexpected-token).
- stripe has a cap on how large a transaction can be (999,999.99 USD) so there's a soft limit to how many users you can have it seems. Have we run into this before?
- in terms of batching groups, do we want to batch based on the number of groups, or the number of users within the groups?

I also still have a few todo's:

- More testing for the sync service (ie. for generateNewHash, buildRequests)
- Refactor the sync call into more testable pieces, potentially move some code that might not belong in this service (looking at some of the directory stuff in this service)

2025-01-06 05:59 UTC, eliykat requested changes
Looking good, here are a few comments but I'll take a closer look once you've finished your draft.

To answer your questions:

> it seems like jest doesnt like ECMAScript Modules (which are used in the googleapis) and plugging it into the existing transformer in the jest config didn't seem to fix it. Not sure how to handle the resulting [error](https://stackoverflow.com/questions/51994111/jest-encountered-an-unexpected-token).

Looking at the [jest documentation](https://jestjs.io/docs/ecmascript-modules), it doesn't have great support for ECMAScript. I think the easiest solution is to decouple the `GsuiteDirectoryService` from `SyncService`, thus avoiding importing the google apis into jest at all. e.g. move `getDirectoryService` to its own class with its own abstraction, and have `SyncService` only inject the abstraction.

This will become a problem again if/when we get a Gsuite testbed set up, but I think that solves it for now, and is a better design.

>    stripe has a cap on how large a transaction can be (999,999.99 USD) so there's a soft limit to how many users you can import and provision seats for at one time. Have we run into this before?

We have not run into this before, but spending $1 million USD in a single provisioning sync seems unlikely. I think we can leave it unhandled.

>    in terms of batching groups, do we want to batch based on the number of groups, or the number of users within the groups?

The goal here is to avoid timeouts at the network edge, so there isn't any hard and fast rule as to how we should split our requests. What do you think?

I can see an argument for splitting based on the number of users in each group - that's the property that scales as you add more users. But my assumption was that these timeouts are actually fairly generous (this request data is very small and this is the first time I've heard of requests timing out), so the simplest approach of batching by _n_ users and _n_ groups would be enough to resolve the issue.

2025-01-06 05:59 UTC, eliykat commented on openldap/ldifs/directory-11000.ldif
This directory is used for integration tests. Because your new service is more or less functional - i.e. it's just processing a set of inputs to a set of outputs - I'm not sure we need dedicated integration tests on it.

If you disagree and want to integration test it, I don't think we should maintain a set of 11k users and 11k groups. Ideally you'd specify a lower batchSize and use a more maintanable set of test data (e.g. 250 users with a batchSize of 45). I recall we discussed trying to replicate real world conditions as much as possible, but this is a lot of fixture data to maintain forever. And would be comparatively slow to run in the pipeline.

2025-01-06 05:59 UTC, eliykat commented on jslib/common/src/services/batching.service.spec.ts
> +    );
I almost always prefer constants in assertions, otherwise you risk rewriting the logic of the SUT.

For example - you know that you've generated 11k users and you have batch sizes of 2k, so you know you're going to have 6 user requests. Assert that your request has a length of 6. (example only, obviously you have groups as well.)

I think it would help with this to specify the `batchSize` in the constructor of the service. That way, the test can specify a fixed batch size and base its assertions on that, without affecting the batch size used by the production code.

2025-01-06 05:59 UTC, eliykat commented on jslib/common/src/services/batching.service.spec.ts
> +      return simulatedArray;
I don't understand why this needs to know about batchSize - it should just generate the number of mock objects requested. Particularly because this is generating mock input data, which is usually supplied by a directory service which knows nothing about batching.

2025-01-20 04:58 UTC, eliykat requested changes
This all looks pretty good! Comments are all fairly minor.

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.ts
> +  async compareToLastHash(hashResult: HashResult): Promise<boolean> {
This name tells us it's doing a comparison, but not what that comparison is or how to interpret the returned result.

Suggestion: `isNewHash` or `hashHasChanged` or similar.

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.ts
> +    // TODO: Remove hashLegacy once we're sure clients have had time to sync new hashes
It's probably too much to do it here, even though it's a simple change, but can you please make a follow-up ticket to remove legacyHash?

2025-01-20 04:58 UTC, eliykat commented on jslib/common/src/services/batch-requests.service.ts
The class name should match the filename. e.g. `BatchRequestBuilder` -> `batch-request-builder.ts` or `batch-request.builder.ts`. Or `BatchRequestBuilderService` -> `batch-request-builder.service.ts`. I don't mind as long as it's consistent. We do tend to call things services but not everything needs to be.

2025-01-20 04:58 UTC, eliykat commented on jslib/common/src/services/batch-requests.service.ts
Also, please add jsdoc comments to these classes, in particular explaining why we've implemented these different ways of building requests.

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    }
I think this would be clearer if you expressly created _n_ requests. Then we don't have to express any batching logic in this test, it's more straightforwardly testing "if given _n_ requests it will send each of them". I think you can just do:

```ts
const mockRequests = new Array(6).fill({
        members: [],
        groups: [],
        overwriteExisting: true,
        largeImport: true,
      });
```

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    expect(apiService.postPublicImportDirectory).toHaveBeenCalledTimes(6);
Suggestion: can you also assert it's been called once with each of the requests?

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    expect(apiService.postPublicImportDirectory).toHaveBeenCalledTimes(0);
I assume this works, but I think it's more idiomatic to use:

```suggestion
    expect(apiService.postPublicImportDirectory).not.toHaveBeenCalled();
```

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    cryptoFunctionService.hash.mockResolvedValue(new ArrayBuffer(0));
I'm missing something here - I can't see that you mock the `stateService.getLastSyncHash` value. How have you mocked/arranged the hash comparison?

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.spec.ts
> +/**
From here down looks like a copy/paste of the integration tests. I suggest rather than duplicating it it's moved into a spec helper file for reuse.

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.ts
> +      const reqJson = JSON.stringify(reqs);
Also, this is subtly changing how the has is generated. A single request used to jsonify to an object, now it's jsonifying to an array containing a single object. It's not a huge deal, but for backwards compatibility I think it would be good to "unwrap" a single request from the array before hashing.

2025-01-20 04:58 UTC, eliykat commented on src/services/sync.service.ts
> +    if (largeImport && groups.length + users.length > 2000) {
This should refer to the `batchSize` constant.

2025-01-20 04:58 UTC, eliykat commented on jslib/common/src/services/batch-requests.service.ts
> +  batchSize = 2000;
Per previous comment - I suggest this is defined as a constant outside of this class so it can be referenced in `SyncService` as well.

2025-01-20 04:58 UTC, eliykat commented on jslib/common/src/services/batch-requests.service.spec.ts
> +  }
This can be simplified:

```ts
return Array(userCount).fill(new UserEntry());
```

2025-01-22 17:31 UTC, BTreston commented on src/services/sync.service.spec.ts
> +    cryptoFunctionService.hash.mockResolvedValue(new ArrayBuffer(0));
Since `cryptoFunctionService.hash` returns an empty ArrayBuffer, the result from the generated hash will not satisfy the first condition in line 94 of the sync service. Its focusing on the wrong condition, relying on generating a falsey hash rather than the result from the comparison call being false.

2025-01-22 19:58 UTC, BTreston commented on jslib/angular/src/services/jslib-services.module.ts
> +import { StateService as StateServiceExtended } from "@/src/abstractions/state.service";
I don't like this naming... open to suggestions. Alternatively we could rename the existing state service since we have 2 (one in jslib and one in src)

2025-01-23 02:50 UTC, eliykat requested changes
There's also a test failure here that I can't explain. Is it actually trying to use apiService somewhere? https://github.com/bitwarden/directory-connector/runs/36020428086#r0s26

2025-01-23 02:50 UTC, eliykat commented on jslib/angular/src/services/jslib-services.module.ts
> +import { StateService as StateServiceExtended } from "@/src/abstractions/state.service";
The src StateService extends the jslib StateService, so you can just use the extended class everywhere and it'll satisfy the type constraints.

However the better answer is that you don't need to add to `jslib-services.module.ts`. Like the rest of the jslib folder, it's essentially deprecated (but I acknowledge this isn't documented anywhere). Register your new dependencies in `src/app/services/services.module.ts`. That file only references the src StateService.

2025-01-23 02:50 UTC, eliykat commented on src/services/sync-config-helpers.ts
I think this needs to be more explicitly marked as test data. e.g. `src/utils/test-fixtures.ts`.

2025-01-23 02:50 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    });
I don't think this should pass - we shouldn't be sending empty request objects to the server.
I expected this would be something like:

```ts
expect(apiService.postPublicImportDirectory).toHaveBeenCalledWith(mockRequests[0]);
expect(apiService.postPublicImportDirectory).toHaveBeenCalledWith(mockRequests[1]);
expect(apiService.postPublicImportDirectory).toHaveBeenCalledWith(mockRequests[2]);
// etc
```

2025-01-23 02:50 UTC, eliykat commented on src/services/default-single-request-builder.ts
This is not a big deal, but I could've been more explicit re: naming.

If you had only 1 request builder class, you might do something like:

```ts
DefaultRequestBuilder extends RequestBuilder
```

This is a most classes where you only have a single implementation.

However, here we do have multiple implementations and we already have a way to distinguish them:

```ts
SingleRequestBuilder extends RequestBuilder
BatchRequestBuilder extends RequestBuilder
// there is no "default" implementation, you have to choose one or the other
```

2025-01-23 02:50 UTC, eliykat commented on src/services/default-batch-requests-builder.spec.ts
>  describe("BatchingService", () => {
Still using the old name

2025-01-31 05:20 UTC, eliykat requested changes

2025-01-31 05:20 UTC, eliykat commented on src/services/default-batch-request-builder.ts
You've duplicated this file instead of renaming it (there is now a `default-batch-request-builder.ts` and a `batch-requests-builder.ts`).

2025-01-31 05:20 UTC, eliykat commented on src/services/sync.service.spec.ts
>      );
Here's how to do this with jest without having to write your own mock implementation and mess around with the types not matching:

```ts
const mockDirectoryService = mock<LdapDirectoryService>();
mockDirectoryService.getEntries.mockResolvedValue([groupFixtures, userFixtures]);
directoryFactory.createService.mockReturnValue(ldapDirectoryService);
```

2025-01-31 05:20 UTC, eliykat commented on src/services/sync.service.spec.ts
> +      apiService as unknown as ApiService,
Why is this type cast necessary?

2025-01-31 05:20 UTC, eliykat commented on src/abstractions/request-builder.service.ts
> +export abstract class RequestBuilderAbstratction {
`Abstraction` suffix is not required:

```suggestion
export abstract class RequestBuilder {
```

(then your names should be good!)

2025-01-31 05:20 UTC, eliykat commented on src/services/sync.service.spec.ts
> +    constants.batchSize = 4;
I'd be interested to know if there's a better way of doing this. This feels hacky, but I don't have any better ideas at the moment. 🤔  It's more important that it's readonly at runtime.

2025-01-31 15:45 UTC, BTreston commented on src/services/sync.service.spec.ts
> +    constants.batchSize = 4;
Yeah not a fan of this either, couldn't come up with anything better. Tried doing jest stuff to mock it but none of the myriad solutions offered through searching quite fit the bill.

2025-01-31 15:47 UTC, BTreston commented on src/services/sync.service.spec.ts
> +      apiService as unknown as ApiService,
Leftover artifact from trying to fix that one test failure.

2025-02-02 23:05 UTC, eliykat approved these changes
Great work, thanks for working through my feedback!

2025-03-10 18:54 UTC, merged