Update electron to 11.1.1
bitwarden/directory-connector pull request #85
Opened 2021-01-13 11:18 UTC by Hinton

Depends on: https://github.com/bitwarden/jslib/pull/247

2021-01-13 18:47 UTC, cscharf reviewed
Looks good, waiting on `jslib` update

2021-01-13 19:59 UTC, kspearrin requested changes

2021-01-13 19:59 UTC, kspearrin commented on package.json
> +    "electron-updater": "4.3.5",
I think some of these need to be updated in src/package.json

2021-01-13 22:35 UTC, Hinton commented on package.json
> +    "electron-updater": "4.3.5",
Correct, one of these days I'll write a test that verifies the versions are in sync ...

2021-01-14 15:30 UTC, kspearrin approved these changes

2021-01-14 15:30 UTC, kspearrin commented
we might want to wait to merge this after this coming release, too.

2021-01-27 14:32 UTC, cscharf reviewed
Hi @Hinton , the following build fails with this update, `npm run dist:cli`

```bash
> bitwarden-directory-connector@0.0.0 pack:cli:lin /Users//source/bitwarden/directory-connector
> pkg . --targets linux-x64 --output ./dist-cli/linux/bwdc

> pkg@4.3.4
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/electron/dist
  path-to-executable/electron/dist
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/sliced/index.js
  path-to-executable/node_modules/sliced/index.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/deep-defaults/lib/index.js
  path-to-executable/node_modules/deep-defaults/index.js
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /Users//source/bitwarden/directory-connector/node_modules/keytar/build/Release/keytar.node
  path-to-executable/keytar.node
npmnpm ERR! code ELIFECYCLE
 ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! errno 2
npmnpm ERR! ERR! bitwarden-directory-connector@0.0.0 pack:cli:win: `pkg . --targets win-x64 --output ./dist-cli/windows/bwdc.exe`
npm bitwarden-directory-connector@0.0.0 pack:cli:mac: `pkg . --targets macos-x64 --output ./dist-cli/macos/bwdc`
 npmERR! ERR! Exit status 2
 Exit status 2
npmnpm  ERR!ERR! 
npm  
ERR!npm  Failed at the bitwarden-directory-connector@0.0.0 pack:cli:mac script.
ERR!npm ERR! Failed at the bitwarden-directory-connector@0.0.0 pack:cli:win script.
 This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-01-27T14_27_48_160Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-01-27T14_27_48_160Z-debug.log
> Error! This experimental syntax requires enabling the parser plugin: 'optionalCatchBinding' (33:10)
  /Users//source/bitwarden/directory-connector/node_modules/electron-updater/node_modules/fs-extra/lib/empty/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitwarden-directory-connector@0.0.0 pack:cli:lin: `pkg . --targets linux-x64 --output ./dist-cli/linux/bwdc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitwarden-directory-connector@0.0.0 pack:cli:lin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-01-27T14_27_48_367Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitwarden-directory-connector@0.0.0 pack:cli: `npm run pack:cli:win | npm run pack:cli:mac | npm run pack:cli:lin`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitwarden-directory-connector@0.0.0 pack:cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-01-27T14_27_48_408Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitwarden-directory-connector@0.0.0 dist:cli: `npm run build:cli:prod && npm run clean:dist:cli && npm run pack:cli`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitwarden-directory-connector@0.0.0 dist:cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-01-27T14_27_48_446Z-debug.log
```

2021-02-03 21:39 UTC, MGibson1 commented
There are definitely commander update issues here. I'll push up a fix for that if no you don't mind, @Hinton

2021-02-03 22:02 UTC, Hinton commented
@cscharf Builds should be working again. MacOS and Windows_gui fails due to missing code signing certs/keys.

2021-02-03 22:08 UTC, cscharf approved these changes

2021-02-03 22:08 UTC, merged