Migrate to gh actions
bitwarden/directory-connector pull request #89
Opened 2021-01-29 18:13 UTC by joseph-flinn

## Summary
Migrating the AppVeyor pipeline to two GitHub Action pipelines: one for building and signing the windows executables and the other for building everything else.

This does not include releasing Linux or MacOS assets.

## Files Changed
- .github/workflows/build.yml
- .github/workflows/release.yml
- scripts/make-versioninfo.ps1
- package.json
- sign.js

## ⚠️ Notes
The signing secrets below can be found in the DevOps Collection

Repo Secrets Needed:

- SIGNING_VAULT_URL
- SIGNING_CLIENT_ID
- SIGNING_CLIENT_SECRET
- SIGNING_TENANT_ID
- SIGNING_CERT_NAME

2021-01-29 18:44 UTC, kspearrin requested changes

2021-01-29 18:44 UTC, kspearrin commented on .github/scripts/macos/decrypt-secrets.ps1
> +Invoke-Expression "& `"$decryptSecretPath`" -filename appstore-installer-cert.p12.gpg"
these dont exist?

2021-01-29 18:44 UTC, kspearrin commented on .github/scripts/macos/increment-version.ps1
> +﻿$rootPath = $env:GITHUB_WORKSPACE;
not sure this is necessary given we are not submitting to app store

2021-01-29 18:44 UTC, kspearrin commented on .github/scripts/macos/setup-keychain.ps1
> +$appstoreAppCertPath = $($secretsPath + "/appstore-app-cert.p12");
some of these not needed?

2021-01-29 18:44 UTC, kspearrin commented on .github/scripts/macos/setup-profiles.ps1
> +$pprofile = "bitwarden_desktop_appstore.provisionprofile"
not needed since no app store

2021-01-29 18:45 UTC, kspearrin commented
i think you need to go through and remove all the stuff related to app stores since we don't submit DC there

2021-01-29 18:48 UTC, joseph-flinn commented
Yep, will do. I think I just did a quick grab of all of the desktop mac stuff and put it in this repo before working on the mac portion. 

This PR doesn't have the mac portion enabled. It is here for if we want to release DC previous to the mac portion being done. I'm also good with waiting if that's what we want to do

2021-02-03 17:10 UTC, kspearrin approved these changes

2021-02-03 17:12 UTC, merged